DROP TABLE ROLE_TABLE IF EXISTS;
DROP TABLE USER_TABLE IF EXISTS;

CREATE TABLE USER_TABLE (
	user_id BIGINT,
	user_name VARCHAR(100) DEFAULT NULL,
	user_password VARCHAR(100) DEFAULT NULL,
	CONSTRAINT pk_user_id PRIMARY KEY (user_id)
);

CREATE TABLE ROLE_TABLE (
	role_id BIGINT,
	role_name VARCHAR(100) DEFAULT NULL,
	role_user_id BIGINT,
	FOREIGN KEY (role_user_id) REFERENCES USER_TABLE (user_id)
);



